import Link from "next/link";
import { auth } from "@/auth";
import { findFile, readJson } from "@/lib/google/drive";
import { ensureAtomicTrackerLayout } from "@/lib/google/drive";
import {
  isoWeekId,
  nextWeekStart,
  type MealPlan,
} from "@/lib/tracker/meal-planner-plan";

const APP_VERSION = "0.1.0";

export default async function PlanPage({
  searchParams,
}: {
  searchParams: { week?: string };
}) {
  const session = await auth();
  const accessToken = session!.accessToken!;
  const googleSub = session!.googleSub!;

  const weekId = searchParams.week ?? isoWeekId(nextWeekStart());

  const layout = await ensureAtomicTrackerLayout(accessToken, {
    googleSub,
    appVersion: APP_VERSION,
  });
  const mealsFolderId = layout.folderIds["history/meals"];

  let plan: MealPlan | null = null;
  if (mealsFolderId) {
    // Try draft first, then accepted
    const draftId =
      (await findFile(accessToken, `${weekId}.draft.json`, mealsFolderId)) ||
      (await findFile(accessToken, `${weekId}.json`, mealsFolderId));
    if (draftId) {
      try {
        plan = await readJson<MealPlan>(accessToken, draftId);
      } catch {
        plan = null;
      }
    }
  }

  return (
    <main className="mx-auto min-h-dvh max-w-md px-6 py-10">
      <header className="flex items-center gap-3">
        <Link
          href="/trackers/meal-planner"
          aria-label="Back"
          className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
        >
          ←
        </Link>
        <div>
          <h1 className="text-lg font-semibold tracking-tight">
            {weekId}
          </h1>
          <p className="text-xs text-slate-500">
            {plan
              ? `${plan.weekStart} → ${plan.weekEnd} · ${
                  plan.status === "draft" ? "Draft" : "Accepted"
                }`
              : "No plan yet"}
          </p>
        </div>
      </header>

      {!plan ? (
        <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-600">
          <p>
            No plan generated for this week yet. Go back and tap{" "}
            <em>Generate next week</em>.
          </p>
        </section>
      ) : (
        <>
          <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 text-xs text-slate-500">
            Generated by{" "}
            <span className="font-medium text-slate-700">
              {plan.generatedBy.provider}
            </span>{" "}
            ({plan.generatedBy.model})
          </section>

          <section className="mt-4 space-y-3">
            {plan.meals.map((m, i) => (
              <article
                key={i}
                className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"
              >
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">
                      {m.day} · {m.cuisine}
                    </p>
                    <h3 className="mt-1 text-base font-semibold text-slate-900">
                      {m.name}
                    </h3>
                  </div>
                  <span className="shrink-0 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-700">
                    {m.calories} kcal
                  </span>
                </div>

                <div className="mt-2 flex flex-wrap gap-1.5 text-[10px]">
                  <Macro label="P" value={m.macros.protein_g} />
                  <Macro label="C" value={m.macros.carbs_g} />
                  <Macro label="F" value={m.macros.fat_g} />
                  <Macro label="Fib" value={m.macros.fiber_g} />
                </div>

                <p className="mt-3 text-xs text-slate-600">{m.health_notes}</p>

                <details className="mt-3 text-xs">
                  <summary className="cursor-pointer text-slate-500 hover:text-slate-900">
                    Ingredients ({m.ingredients.length})
                  </summary>
                  <ul className="mt-2 space-y-0.5 text-slate-700">
                    {m.ingredients.map((ing, j) => (
                      <li key={j}>
                        {ing.qty} {ing.unit} {ing.name}
                      </li>
                    ))}
                  </ul>
                </details>

                <details className="mt-2 text-xs">
                  <summary className="cursor-pointer text-slate-500 hover:text-slate-900">
                    Instructions
                  </summary>
                  <p className="mt-2 text-slate-700">{m.instructions}</p>
                </details>

                {m.recipe_url ? (
                  <a
                    href={m.recipe_url}
                    target="_blank"
                    rel="noreferrer"
                    className="mt-3 inline-flex items-center gap-1 rounded-lg border border-red-200 bg-red-50 px-2.5 py-1 text-[11px] font-medium text-red-700 hover:bg-red-100"
                  >
                    ▶ Recipe video search
                  </a>
                ) : null}
              </article>
            ))}
          </section>

          <section className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-600">
            <p className="font-medium text-slate-900">Next: review &amp; accept</p>
            <p className="mt-2">
              Commit 7 adds swap/lock/regenerate per meal and a chat panel.
              Commit 8 adds the accept flow that writes the grocery CSV and the
              recurring Calendar reminders.
            </p>
          </section>
        </>
      )}
    </main>
  );
}

function Macro({ label, value }: { label: string; value: number }) {
  return (
    <span className="rounded-md bg-slate-100 px-2 py-0.5 text-slate-700">
      {label} <span className="font-semibold">{value}</span>g
    </span>
  );
}
