"use client";

import { useState } from "react";
import { decryptJson } from "@/lib/crypto/webcrypto";
import { loadPassphrase } from "@/lib/storage/passphrase";
import type { ProviderId } from "@/lib/ai/providers";
import { readConnectorEnvelope } from "@/app/settings/actions";
import type { Day, Meal, MealPlan } from "@/lib/tracker/meal-planner-plan";

type ConnectorsPayload = {
  v: 1;
  ai?: { provider: ProviderId; apiKey: string; addedAt: string };
};

async function getKey(googleSub: string) {
  const passphrase = await loadPassphrase();
  if (!passphrase) throw new Error("Set passphrase in Settings first");
  const envelope = await readConnectorEnvelope();
  if (!envelope) throw new Error("Connect an AI provider in Settings first");
  const payload = await decryptJson<ConnectorsPayload>(envelope, passphrase, googleSub);
  if (!payload.ai) throw new Error("No AI provider configured");
  return { provider: payload.ai.provider, apiKey: payload.ai.apiKey };
}

export function PlanClient({
  initialPlan,
  googleSub,
}: {
  initialPlan: MealPlan;
  googleSub: string;
}) {
  const [plan, setPlan] = useState<MealPlan>(initialPlan);
  const [busyDay, setBusyDay] = useState<Day | "all" | null>(null);
  const [error, setError] = useState<string | null>(null);

  function toggleLock(day: Day) {
    setPlan((p) => ({
      ...p,
      meals: p.meals.map((m) =>
        m.day === day ? { ...m, locked: !m.locked } : m,
      ),
    }));
    // Note: we save to Drive only on swap/regenerate.
    // Lock state lives in memory until a network change triggers a write.
  }

  async function swapDay(day: Day) {
    setError(null);
    setBusyDay(day);
    try {
      const { provider, apiKey } = await getKey(googleSub);
      const res = await fetch("/api/swap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ provider, apiKey, plan, dayToSwap: day }),
      });
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        throw new Error((j as { error?: string }).error ?? `${res.status}`);
      }
      const data = (await res.json()) as { plan: MealPlan };
      // Preserve client-side locked flags on un-swapped days
      const merged: MealPlan = {
        ...data.plan,
        meals: data.plan.meals.map((newM) => {
          const oldM = plan.meals.find((x) => x.day === newM.day);
          if (newM.day === day) return newM;
          return { ...newM, locked: oldM?.locked };
        }),
      };
      setPlan(merged);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusyDay(null);
    }
  }

  async function regenerateAll() {
    setError(null);
    setBusyDay("all");
    try {
      const { provider, apiKey } = await getKey(googleSub);
      const lockedDays = plan.meals.filter((m) => m.locked).map((m) => m.day);
      const res = await fetch("/api/regenerate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ provider, apiKey, plan, lockedDays }),
      });
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        throw new Error((j as { error?: string }).error ?? `${res.status}`);
      }
      const data = (await res.json()) as { plan: MealPlan };
      setPlan(data.plan);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusyDay(null);
    }
  }

  const lockedCount = plan.meals.filter((m) => m.locked).length;
  const allLocked = lockedCount === 7;

  return (
    <>
      <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4">
        <div className="flex items-center justify-between">
          <p className="text-xs text-slate-500">
            Generated by{" "}
            <span className="font-medium text-slate-700">
              {plan.generatedBy.provider}
            </span>{" "}
            ({plan.generatedBy.model})
          </p>
          {lockedCount > 0 ? (
            <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-medium text-amber-900">
              🔒 {lockedCount}/7 locked
            </span>
          ) : null}
        </div>
        <button
          type="button"
          onClick={regenerateAll}
          disabled={busyDay !== null || allLocked}
          className="mt-3 w-full rounded-xl border border-brand-300 bg-brand-50 px-4 py-2.5 text-sm font-semibold text-brand-700 hover:bg-brand-100 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {busyDay === "all"
            ? "Regenerating…"
            : allLocked
              ? "All meals locked"
              : `Regenerate ${7 - lockedCount} unlocked meals`}
        </button>
        {error ? (
          <p className="mt-2 rounded-lg border border-red-200 bg-red-50 p-2 text-xs text-red-900">
            {error}
          </p>
        ) : null}
      </section>

      <section className="mt-4 space-y-3">
        {plan.meals.map((m) => (
          <MealCard
            key={m.day}
            meal={m}
            busy={busyDay === m.day || busyDay === "all"}
            onLock={() => toggleLock(m.day)}
            onSwap={() => swapDay(m.day)}
          />
        ))}
      </section>

      <section className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-600">
        <p className="font-medium text-slate-900">Next: chat &amp; accept</p>
        <p className="mt-2">
          Commit 8 adds a chat panel and the accept flow that writes the
          grocery CSV (with Walmart/Amazon/DoorDash search URLs) and creates
          the recurring Friday/Sunday Calendar reminders.
        </p>
      </section>
    </>
  );
}

function MealCard({
  meal,
  busy,
  onLock,
  onSwap,
}: {
  meal: Meal;
  busy: boolean;
  onLock: () => void;
  onSwap: () => void;
}) {
  return (
    <article
      className={`rounded-2xl border bg-white p-4 shadow-sm transition ${
        meal.locked ? "border-amber-300 ring-1 ring-amber-200" : "border-slate-200"
      } ${busy ? "opacity-60" : ""}`}
    >
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">
            {meal.day} · {meal.cuisine}
          </p>
          <h3 className="mt-1 text-base font-semibold text-slate-900">
            {meal.name}
          </h3>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <button
            type="button"
            onClick={onLock}
            disabled={busy}
            aria-label={meal.locked ? "Unlock meal" : "Lock meal"}
            title={meal.locked ? "Unlock" : "Lock — won't be replaced on regenerate"}
            className={`grid h-8 w-8 place-items-center rounded-lg text-base transition ${
              meal.locked
                ? "bg-amber-100 text-amber-700 hover:bg-amber-200"
                : "border border-slate-200 bg-white text-slate-400 hover:bg-slate-50"
            } disabled:opacity-50`}
          >
            {meal.locked ? "🔒" : "🔓"}
          </button>
          <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-700">
            {meal.calories} kcal
          </span>
        </div>
      </div>

      <div className="mt-2 flex flex-wrap gap-1.5 text-[10px]">
        <Macro label="P" value={meal.macros.protein_g} />
        <Macro label="C" value={meal.macros.carbs_g} />
        <Macro label="F" value={meal.macros.fat_g} />
        <Macro label="Fib" value={meal.macros.fiber_g} />
      </div>

      <p className="mt-3 text-xs text-slate-600">{meal.health_notes}</p>

      <details className="mt-3 text-xs">
        <summary className="cursor-pointer text-slate-500 hover:text-slate-900">
          Ingredients ({meal.ingredients.length})
        </summary>
        <ul className="mt-2 space-y-0.5 text-slate-700">
          {meal.ingredients.map((ing, j) => (
            <li key={j}>
              {ing.qty} {ing.unit} {ing.name}
            </li>
          ))}
        </ul>
      </details>

      <details className="mt-2 text-xs">
        <summary className="cursor-pointer text-slate-500 hover:text-slate-900">
          Instructions
        </summary>
        <p className="mt-2 text-slate-700">{meal.instructions}</p>
      </details>

      <div className="mt-3 flex items-center gap-2">
        {meal.recipe_url ? (
          <a
            href={meal.recipe_url}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1 rounded-lg border border-red-200 bg-red-50 px-2.5 py-1 text-[11px] font-medium text-red-700 hover:bg-red-100"
          >
            ▶ Recipe video
          </a>
        ) : null}
        <button
          type="button"
          onClick={onSwap}
          disabled={busy || meal.locked}
          className="ml-auto inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-2.5 py-1 text-[11px] font-medium text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {busy ? "…" : meal.locked ? "Locked" : "↻ Swap"}
        </button>
      </div>
    </article>
  );
}

function Macro({ label, value }: { label: string; value: number }) {
  return (
    <span className="rounded-md bg-slate-100 px-2 py-0.5 text-slate-700">
      {label} <span className="font-semibold">{value}</span>g
    </span>
  );
}
